//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowerShop.EntityModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class FlowerShopEntities : DbContext
    {
        public FlowerShopEntities()
            : base("name=FlowerShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Category> Categories { get; set; }
        public DbSet<Contact> Contacts { get; set; }
        public DbSet<Orderdetail> Orderdetails { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TinTuc> TinTucs { get; set; }
        public DbSet<user> users { get; set; }
        public DbSet<View_DonHang> View_DonHang { get; set; }
    
        public virtual ObjectResult<Nullable<decimal>> category_add(string parentid, string names, Nullable<int> no, Nullable<bool> active)
        {
            var parentidParameter = parentid != null ?
                new ObjectParameter("parentid", parentid) :
                new ObjectParameter("parentid", typeof(string));
    
            var namesParameter = names != null ?
                new ObjectParameter("names", names) :
                new ObjectParameter("names", typeof(string));
    
            var noParameter = no.HasValue ?
                new ObjectParameter("no", no) :
                new ObjectParameter("no", typeof(int));
    
            var activeParameter = active.HasValue ?
                new ObjectParameter("active", active) :
                new ObjectParameter("active", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("category_add", parentidParameter, namesParameter, noParameter, activeParameter);
        }
    
        public virtual int category_delete(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("category_delete", idParameter);
        }
    
        public virtual ObjectResult<category_get_Result> category_get(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<category_get_Result>("category_get", idParameter);
        }
    
        public virtual ObjectResult<category_getall_Result> category_getall()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<category_getall_Result>("category_getall");
        }
    
        public virtual ObjectResult<category_GetDanhMucCon_Result> category_GetDanhMucCon(Nullable<bool> active)
        {
            var activeParameter = active.HasValue ?
                new ObjectParameter("active", active) :
                new ObjectParameter("active", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<category_GetDanhMucCon_Result>("category_GetDanhMucCon", activeParameter);
        }
    
        public virtual int category_update(Nullable<int> id, string parentid, string names, Nullable<int> no, Nullable<bool> active)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var parentidParameter = parentid != null ?
                new ObjectParameter("parentid", parentid) :
                new ObjectParameter("parentid", typeof(string));
    
            var namesParameter = names != null ?
                new ObjectParameter("names", names) :
                new ObjectParameter("names", typeof(string));
    
            var noParameter = no.HasValue ?
                new ObjectParameter("no", no) :
                new ObjectParameter("no", typeof(int));
    
            var activeParameter = active.HasValue ?
                new ObjectParameter("active", active) :
                new ObjectParameter("active", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("category_update", idParameter, parentidParameter, namesParameter, noParameter, activeParameter);
        }
    
        public virtual int category_update_TrangThai(Nullable<int> id, Nullable<bool> status)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("category_update_TrangThai", idParameter, statusParameter);
        }
    
        public virtual int changepass(Nullable<int> id, string pass)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("changepass", idParameter, passParameter);
        }
    
        public virtual int contact_add(string hoten, string email, string phone, string noidung, Nullable<bool> trangThai)
        {
            var hotenParameter = hoten != null ?
                new ObjectParameter("hoten", hoten) :
                new ObjectParameter("hoten", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var noidungParameter = noidung != null ?
                new ObjectParameter("noidung", noidung) :
                new ObjectParameter("noidung", typeof(string));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("contact_add", hotenParameter, emailParameter, phoneParameter, noidungParameter, trangThaiParameter);
        }
    
        public virtual int contact_delete(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("contact_delete", idParameter);
        }
    
        public virtual int contact_get(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("contact_get", idParameter);
        }
    
        public virtual ObjectResult<contact_getall_Result> contact_getall()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<contact_getall_Result>("contact_getall");
        }
    
        public virtual ObjectResult<contact_GetXuLy_Result> contact_GetXuLy(Nullable<bool> trangThai)
        {
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<contact_GetXuLy_Result>("contact_GetXuLy", trangThaiParameter);
        }
    
        public virtual int contact_update(Nullable<int> id, Nullable<bool> trangthai)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var trangthaiParameter = trangthai.HasValue ?
                new ObjectParameter("trangthai", trangthai) :
                new ObjectParameter("trangthai", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("contact_update", idParameter, trangthaiParameter);
        }
    
        public virtual ObjectResult<getchild_Result> getchild(string idca, string active)
        {
            var idcaParameter = idca != null ?
                new ObjectParameter("idca", idca) :
                new ObjectParameter("idca", typeof(string));
    
            var activeParameter = active != null ?
                new ObjectParameter("active", active) :
                new ObjectParameter("active", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getchild_Result>("getchild", idcaParameter, activeParameter);
        }
    
        public virtual ObjectResult<getparent_Result> getparent(string active)
        {
            var activeParameter = active != null ?
                new ObjectParameter("active", active) :
                new ObjectParameter("active", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getparent_Result>("getparent", activeParameter);
        }
    
        public virtual int menu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("menu");
        }
    
        public virtual int Orderdetails_Delete(Nullable<int> orderid, Nullable<int> productsId)
        {
            var orderidParameter = orderid.HasValue ?
                new ObjectParameter("orderid", orderid) :
                new ObjectParameter("orderid", typeof(int));
    
            var productsIdParameter = productsId.HasValue ?
                new ObjectParameter("ProductsId", productsId) :
                new ObjectParameter("ProductsId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Orderdetails_Delete", orderidParameter, productsIdParameter);
        }
    
        public virtual ObjectResult<Orderdetails_GetById_Result> Orderdetails_GetById(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Orderdetails_GetById_Result>("Orderdetails_GetById", idParameter);
        }
    
        public virtual int Orderdetails_Insert(Nullable<int> orderid, Nullable<int> productsId, Nullable<int> soLuong)
        {
            var orderidParameter = orderid.HasValue ?
                new ObjectParameter("orderid", orderid) :
                new ObjectParameter("orderid", typeof(int));
    
            var productsIdParameter = productsId.HasValue ?
                new ObjectParameter("ProductsId", productsId) :
                new ObjectParameter("ProductsId", typeof(int));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Orderdetails_Insert", orderidParameter, productsIdParameter, soLuongParameter);
        }
    
        public virtual int Orderdetails_Update(Nullable<int> orderid, Nullable<int> productsId, Nullable<int> soLuong)
        {
            var orderidParameter = orderid.HasValue ?
                new ObjectParameter("orderid", orderid) :
                new ObjectParameter("orderid", typeof(int));
    
            var productsIdParameter = productsId.HasValue ?
                new ObjectParameter("ProductsId", productsId) :
                new ObjectParameter("ProductsId", typeof(int));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Orderdetails_Update", orderidParameter, productsIdParameter, soLuongParameter);
        }
    
        public virtual int Orders_Delete(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Orders_Delete", idParameter);
        }
    
        public virtual ObjectResult<Orders_GetAll_Result> Orders_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Orders_GetAll_Result>("Orders_GetAll");
        }
    
        public virtual ObjectResult<Orders_GetById_Result> Orders_GetById(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Orders_GetById_Result>("Orders_GetById", idParameter);
        }
    
        public virtual ObjectResult<Orders_GetTrangThai_Result> Orders_GetTrangThai(Nullable<bool> trangthai)
        {
            var trangthaiParameter = trangthai.HasValue ?
                new ObjectParameter("trangthai", trangthai) :
                new ObjectParameter("trangthai", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Orders_GetTrangThai_Result>("Orders_GetTrangThai", trangthaiParameter);
        }
    
        public virtual int Orders_Insert(ObjectParameter id, string tenKhachHang, string diaChi, string email, string phone, string ghiChu, Nullable<double> tongTien, Nullable<bool> status)
        {
            var tenKhachHangParameter = tenKhachHang != null ?
                new ObjectParameter("TenKhachHang", tenKhachHang) :
                new ObjectParameter("TenKhachHang", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("Phone", phone) :
                new ObjectParameter("Phone", typeof(string));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("GhiChu", ghiChu) :
                new ObjectParameter("GhiChu", typeof(string));
    
            var tongTienParameter = tongTien.HasValue ?
                new ObjectParameter("TongTien", tongTien) :
                new ObjectParameter("TongTien", typeof(double));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Orders_Insert", id, tenKhachHangParameter, diaChiParameter, emailParameter, phoneParameter, ghiChuParameter, tongTienParameter, statusParameter);
        }
    
        public virtual int Orders_Update(Nullable<int> id, string tenKhachHang, string diaChi, string email, string phone, string ghiChu, Nullable<double> tongTien, Nullable<bool> status)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var tenKhachHangParameter = tenKhachHang != null ?
                new ObjectParameter("TenKhachHang", tenKhachHang) :
                new ObjectParameter("TenKhachHang", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("Phone", phone) :
                new ObjectParameter("Phone", typeof(string));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("GhiChu", ghiChu) :
                new ObjectParameter("GhiChu", typeof(string));
    
            var tongTienParameter = tongTien.HasValue ?
                new ObjectParameter("TongTien", tongTien) :
                new ObjectParameter("TongTien", typeof(double));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Orders_Update", idParameter, tenKhachHangParameter, diaChiParameter, emailParameter, phoneParameter, ghiChuParameter, tongTienParameter, statusParameter);
        }
    
        public virtual int products_Active(Nullable<bool> status, Nullable<int> id)
        {
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(bool));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("products_Active", statusParameter, idParameter);
        }
    
        public virtual int Products_add(Nullable<int> id_item, string pname, string pmota, string pchitiet, Nullable<double> ppricecurrent, Nullable<double> ppriceold, string pimage, Nullable<bool> pnew, Nullable<bool> pkhuyenmai, Nullable<bool> phot, string pngaydang, Nullable<bool> active)
        {
            var id_itemParameter = id_item.HasValue ?
                new ObjectParameter("id_item", id_item) :
                new ObjectParameter("id_item", typeof(int));
    
            var pnameParameter = pname != null ?
                new ObjectParameter("pname", pname) :
                new ObjectParameter("pname", typeof(string));
    
            var pmotaParameter = pmota != null ?
                new ObjectParameter("pmota", pmota) :
                new ObjectParameter("pmota", typeof(string));
    
            var pchitietParameter = pchitiet != null ?
                new ObjectParameter("pchitiet", pchitiet) :
                new ObjectParameter("pchitiet", typeof(string));
    
            var ppricecurrentParameter = ppricecurrent.HasValue ?
                new ObjectParameter("ppricecurrent", ppricecurrent) :
                new ObjectParameter("ppricecurrent", typeof(double));
    
            var ppriceoldParameter = ppriceold.HasValue ?
                new ObjectParameter("ppriceold", ppriceold) :
                new ObjectParameter("ppriceold", typeof(double));
    
            var pimageParameter = pimage != null ?
                new ObjectParameter("pimage", pimage) :
                new ObjectParameter("pimage", typeof(string));
    
            var pnewParameter = pnew.HasValue ?
                new ObjectParameter("pnew", pnew) :
                new ObjectParameter("pnew", typeof(bool));
    
            var pkhuyenmaiParameter = pkhuyenmai.HasValue ?
                new ObjectParameter("pkhuyenmai", pkhuyenmai) :
                new ObjectParameter("pkhuyenmai", typeof(bool));
    
            var photParameter = phot.HasValue ?
                new ObjectParameter("phot", phot) :
                new ObjectParameter("phot", typeof(bool));
    
            var pngaydangParameter = pngaydang != null ?
                new ObjectParameter("pngaydang", pngaydang) :
                new ObjectParameter("pngaydang", typeof(string));
    
            var activeParameter = active.HasValue ?
                new ObjectParameter("active", active) :
                new ObjectParameter("active", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Products_add", id_itemParameter, pnameParameter, pmotaParameter, pchitietParameter, ppricecurrentParameter, ppriceoldParameter, pimageParameter, pnewParameter, pkhuyenmaiParameter, photParameter, pngaydangParameter, activeParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Products_count()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Products_count");
        }
    
        public virtual int Products_Del_pro(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Products_Del_pro", idParameter);
        }
    
        public virtual ObjectResult<Products_Get_By_DanhMucCha_Result> Products_Get_By_DanhMucCha(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Products_Get_By_DanhMucCha_Result>("Products_Get_By_DanhMucCha", idParameter);
        }
    
        public virtual ObjectResult<products_GetAll_Result> products_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<products_GetAll_Result>("products_GetAll");
        }
    
        public virtual ObjectResult<Products_Getby_option_Result> Products_Getby_option(string option)
        {
            var optionParameter = option != null ?
                new ObjectParameter("option", option) :
                new ObjectParameter("option", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Products_Getby_option_Result>("Products_Getby_option", optionParameter);
        }
    
        public virtual ObjectResult<Products_getdetail_Result> Products_getdetail(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Products_getdetail_Result>("Products_getdetail", idParameter);
        }
    
        public virtual int Products_GetHot()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Products_GetHot");
        }
    
        public virtual ObjectResult<Products_Getnameitem_Result> Products_Getnameitem(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Products_Getnameitem_Result>("Products_Getnameitem", idParameter);
        }
    
        public virtual int Products_GetNew()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Products_GetNew");
        }
    
        public virtual ObjectResult<Products_getpro_Result> Products_getpro()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Products_getpro_Result>("Products_getpro");
        }
    
        public virtual ObjectResult<Products_Getpro_by_Result> Products_Getpro_by(string iditem)
        {
            var iditemParameter = iditem != null ?
                new ObjectParameter("iditem", iditem) :
                new ObjectParameter("iditem", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Products_Getpro_by_Result>("Products_Getpro_by", iditemParameter);
        }
    
        public virtual int Products_getpro_parent(Nullable<int> id, Nullable<int> quantity)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("quantity", quantity) :
                new ObjectParameter("quantity", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Products_getpro_parent", idParameter, quantityParameter);
        }
    
        public virtual int Products_GetSaLe(Nullable<bool> khuyenmai)
        {
            var khuyenmaiParameter = khuyenmai.HasValue ?
                new ObjectParameter("khuyenmai", khuyenmai) :
                new ObjectParameter("khuyenmai", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Products_GetSaLe", khuyenmaiParameter);
        }
    
        public virtual ObjectResult<products_sanphamcungloai_Result> products_sanphamcungloai(Nullable<int> soluong, Nullable<int> iddanhmuc, Nullable<int> id)
        {
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(int));
    
            var iddanhmucParameter = iddanhmuc.HasValue ?
                new ObjectParameter("iddanhmuc", iddanhmuc) :
                new ObjectParameter("iddanhmuc", typeof(int));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<products_sanphamcungloai_Result>("products_sanphamcungloai", soluongParameter, iddanhmucParameter, idParameter);
        }
    
        public virtual ObjectResult<products_TimKiem_Result> products_TimKiem(string key)
        {
            var keyParameter = key != null ?
                new ObjectParameter("key", key) :
                new ObjectParameter("key", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<products_TimKiem_Result>("products_TimKiem", keyParameter);
        }
    
        public virtual int Products_update(Nullable<int> id, Nullable<int> id_item, string pname, string pmota, string pchitiet, Nullable<double> ppricecurrent, Nullable<double> ppriceold, string pimage, Nullable<bool> pnew, Nullable<bool> pkhuyenmai, Nullable<bool> phot, string pngaydang, Nullable<bool> active)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var id_itemParameter = id_item.HasValue ?
                new ObjectParameter("id_item", id_item) :
                new ObjectParameter("id_item", typeof(int));
    
            var pnameParameter = pname != null ?
                new ObjectParameter("pname", pname) :
                new ObjectParameter("pname", typeof(string));
    
            var pmotaParameter = pmota != null ?
                new ObjectParameter("pmota", pmota) :
                new ObjectParameter("pmota", typeof(string));
    
            var pchitietParameter = pchitiet != null ?
                new ObjectParameter("pchitiet", pchitiet) :
                new ObjectParameter("pchitiet", typeof(string));
    
            var ppricecurrentParameter = ppricecurrent.HasValue ?
                new ObjectParameter("ppricecurrent", ppricecurrent) :
                new ObjectParameter("ppricecurrent", typeof(double));
    
            var ppriceoldParameter = ppriceold.HasValue ?
                new ObjectParameter("ppriceold", ppriceold) :
                new ObjectParameter("ppriceold", typeof(double));
    
            var pimageParameter = pimage != null ?
                new ObjectParameter("pimage", pimage) :
                new ObjectParameter("pimage", typeof(string));
    
            var pnewParameter = pnew.HasValue ?
                new ObjectParameter("pnew", pnew) :
                new ObjectParameter("pnew", typeof(bool));
    
            var pkhuyenmaiParameter = pkhuyenmai.HasValue ?
                new ObjectParameter("pkhuyenmai", pkhuyenmai) :
                new ObjectParameter("pkhuyenmai", typeof(bool));
    
            var photParameter = phot.HasValue ?
                new ObjectParameter("phot", phot) :
                new ObjectParameter("phot", typeof(bool));
    
            var pngaydangParameter = pngaydang != null ?
                new ObjectParameter("pngaydang", pngaydang) :
                new ObjectParameter("pngaydang", typeof(string));
    
            var activeParameter = active.HasValue ?
                new ObjectParameter("active", active) :
                new ObjectParameter("active", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Products_update", idParameter, id_itemParameter, pnameParameter, pmotaParameter, pchitietParameter, ppricecurrentParameter, ppriceoldParameter, pimageParameter, pnewParameter, pkhuyenmaiParameter, photParameter, pngaydangParameter, activeParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int TinTuc_Delete(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TinTuc_Delete", idParameter);
        }
    
        public virtual ObjectResult<TinTuc_GetAll_Result> TinTuc_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TinTuc_GetAll_Result>("TinTuc_GetAll");
        }
    
        public virtual ObjectResult<TinTuc_GetById_Result> TinTuc_GetById(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TinTuc_GetById_Result>("TinTuc_GetById", idParameter);
        }
    
        public virtual int TinTuc_Insert(string hinhDaiDien, string tieuDe, string tomTat, string noiDung, Nullable<System.DateTime> ngayDang, Nullable<bool> trangThai)
        {
            var hinhDaiDienParameter = hinhDaiDien != null ?
                new ObjectParameter("HinhDaiDien", hinhDaiDien) :
                new ObjectParameter("HinhDaiDien", typeof(string));
    
            var tieuDeParameter = tieuDe != null ?
                new ObjectParameter("TieuDe", tieuDe) :
                new ObjectParameter("TieuDe", typeof(string));
    
            var tomTatParameter = tomTat != null ?
                new ObjectParameter("TomTat", tomTat) :
                new ObjectParameter("TomTat", typeof(string));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("NoiDung", noiDung) :
                new ObjectParameter("NoiDung", typeof(string));
    
            var ngayDangParameter = ngayDang.HasValue ?
                new ObjectParameter("NgayDang", ngayDang) :
                new ObjectParameter("NgayDang", typeof(System.DateTime));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TinTuc_Insert", hinhDaiDienParameter, tieuDeParameter, tomTatParameter, noiDungParameter, ngayDangParameter, trangThaiParameter);
        }
    
        public virtual int TinTuc_Update(Nullable<int> id, string hinhDaiDien, string tieuDe, string tomTat, string noiDung, Nullable<bool> trangThai)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var hinhDaiDienParameter = hinhDaiDien != null ?
                new ObjectParameter("HinhDaiDien", hinhDaiDien) :
                new ObjectParameter("HinhDaiDien", typeof(string));
    
            var tieuDeParameter = tieuDe != null ?
                new ObjectParameter("TieuDe", tieuDe) :
                new ObjectParameter("TieuDe", typeof(string));
    
            var tomTatParameter = tomTat != null ?
                new ObjectParameter("TomTat", tomTat) :
                new ObjectParameter("TomTat", typeof(string));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("NoiDung", noiDung) :
                new ObjectParameter("NoiDung", typeof(string));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TinTuc_Update", idParameter, hinhDaiDienParameter, tieuDeParameter, tomTatParameter, noiDungParameter, trangThaiParameter);
        }
    
        public virtual int users_add(string username, string email, string password, string fullname, string address, string birdthday, string phone, string rolecode, Nullable<bool> status)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var fullnameParameter = fullname != null ?
                new ObjectParameter("fullname", fullname) :
                new ObjectParameter("fullname", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            var birdthdayParameter = birdthday != null ?
                new ObjectParameter("birdthday", birdthday) :
                new ObjectParameter("birdthday", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var rolecodeParameter = rolecode != null ?
                new ObjectParameter("rolecode", rolecode) :
                new ObjectParameter("rolecode", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("users_add", usernameParameter, emailParameter, passwordParameter, fullnameParameter, addressParameter, birdthdayParameter, phoneParameter, rolecodeParameter, statusParameter);
        }
    
        public virtual ObjectResult<users_checkmail_Result> users_checkmail(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<users_checkmail_Result>("users_checkmail", emailParameter);
        }
    
        public virtual ObjectResult<users_checkuser_Result> users_checkuser(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<users_checkuser_Result>("users_checkuser", usernameParameter);
        }
    
        public virtual int users_Delete(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("users_Delete", idParameter);
        }
    
        public virtual int users_doipass(Nullable<int> id, string pass)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("users_doipass", idParameter, passParameter);
        }
    
        public virtual ObjectResult<users_getall_Result> users_getall()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<users_getall_Result>("users_getall");
        }
    
        public virtual ObjectResult<users_getbyid_Result> users_getbyid(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<users_getbyid_Result>("users_getbyid", idParameter);
        }
    
        public virtual int users_Update(Nullable<int> id, string email, string password, string fullname, string address, string birdthday, string phone, string rolecode, Nullable<bool> status)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var fullnameParameter = fullname != null ?
                new ObjectParameter("fullname", fullname) :
                new ObjectParameter("fullname", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            var birdthdayParameter = birdthday != null ?
                new ObjectParameter("birdthday", birdthday) :
                new ObjectParameter("birdthday", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var rolecodeParameter = rolecode != null ?
                new ObjectParameter("rolecode", rolecode) :
                new ObjectParameter("rolecode", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("users_Update", idParameter, emailParameter, passwordParameter, fullnameParameter, addressParameter, birdthdayParameter, phoneParameter, rolecodeParameter, statusParameter);
        }
    }
}
