//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowerShop.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orderdetail
    {
        public int Orderid { get; set; }
        public int ProductsId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> SoLuong { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
