//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowerShop.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Orderdetails = new HashSet<Orderdetail>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_item { get; set; }
        public string pName { get; set; }
        public string pDetail { get; set; }
        public string pDescriptions { get; set; }
        public Nullable<double> pPricecurrent { get; set; }
        public Nullable<double> pPriceold { get; set; }
        public string pImage { get; set; }
        public Nullable<bool> pNew { get; set; }
        public Nullable<bool> pPromotion { get; set; }
        public Nullable<bool> pHot { get; set; }
        public string pModify { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Orderdetail> Orderdetails { get; set; }
    }
}
