//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowerShop.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_DonHang
    {
        public int orderid { get; set; }
        public int ProductsId { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public int id { get; set; }
        public string TenKhachHang { get; set; }
        public string DiaChi { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string GhiChu { get; set; }
        public Nullable<double> TongTien { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
